### PR TITLE
fix: improve Shabad info popup formatting

### LINKED ISSUE #470: Fix formatting of pop-up info
image

### LINKED ISSUE #471: Fix formatting of "copy shabad"
`ਦੋਹਰਾ ॥ਸਗਲ ਦੁਆਰ ਕਉ ਛਾਡਿ ਕੈ ਗਹਯੋ ਤੁਹਾਰੋ ਦੁਆਰ ॥ਬਾਹਿ ਗਹੇ ਕੀ ਲਾਜ ਅਸਿ ਗੋਬਿੰਦ ਦਾਸ ਤੁਹਾਰ ॥੮੬੪॥ਇਤਿ ਸ੍ਰੀ ਰਾਮਾਇਣ ਸਮਾਪਤਮ ਸਤੁ ਸੁਭਮ ਸਤੁ ॥`

Add spaces

### PR DESCRIPTION
**Pull request by saihaj**
closes #470 
closes #471

### CODE REVIEW

File: app/frontend/src/Controller/ShabadInfo.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ const ShabadInfo = () => {
   const barIcon = isPopoverOpen ? faTimesCircle : faInfoCircle
 
   const onCopyClick = () => {
-    const gurmukhi = lines.reduce( ( text, { gurmukhi } ) => `${text}${gurmukhi}`, '' )
+    const gurmukhi = lines.reduce( ( text, { gurmukhi } ) => `${text}${gurmukhi} `, '' )
```
Comment (bhajneet) [inline app/frontend/src/Controller/ShabadInfo.js:42]: Would this not cause an empty space at the end of the string?

Comment (AkalUstat) [reply app/frontend/src/Controller/ShabadInfo.js:42]: if he had done `' '` instead of `''`,  that would have caused an empty space

Comment (AkalUstat) [reply app/frontend/src/Controller/ShabadInfo.js:42]: wait no you're right there would be one extra at the end

Comment (saihaj) [reply app/frontend/src/Controller/ShabadInfo.js:42]: I tried that first but didn't work.
> if he had done `' '` instead of `''`, that would have caused an empty space

Comment (saihaj) [reply app/frontend/src/Controller/ShabadInfo.js:42]: > Would this not cause an empty space at the end of the string?

That is what we want. We are just making a long string by concatenating the lines.

Comment (Harjot1Singh) [reply app/frontend/src/Controller/ShabadInfo.js:42]: We do not want an exmpty space at the end of the string. Another way:

```suggestion
    const gurmukhi = lines.map( ( { gurmukhi } ) => gurmukhi ).join( ' ' )
```

This will only insert spaces in-between array elements
