### PR TITLE
fix(frontend/presenter): clicking on plus should not toggle next line

### LINKED ISSUE #401: Don't advance line when clicking "+" sign to open controller

### PR DESCRIPTION
**Pull request by AkalUstat**
excludes the classNames which are not 'desktop app' or 'presenter'

fixes #401

### CODE REVIEW

**Comment by bhajneet** [comment]
This looks good to me. Pending final review from Harjot.

@AkalUstat In future please use the imperative mood in commit messages ([rule 5](https://chris.beams.io/posts/git-commit/#imperative)), meaning "as if giving a command or instruction". So a very small change from `fix(frontend): clicking on plus will not activate line switch` to `fix(frontend): click on plus will not activate line switch`. This time is fine, you don't have to amend the commit.

@Harjot1Singh might be best to link this in our commit guidelines if not done so already

File: app/frontend/src/shared/NavigatorHotkeys.js [hunk 1]
```diff
@@ -72,7 +72,9 @@ const NavigatorHotKeys = ( { active, children, mouseTargetRef } ) => {
     }
   }, [ lines, lineId ] )
 
-  const goNextLine = useCallback( () => {
+  const goNextLine = useCallback((e) => {
+    // exclude anything other than the main window
+    if( e.target.parentNode.className !== 'desktop app' && e.target.parentNode.className !== 'presenter' ) return
```
Comment (Harjot1Singh) [inline app/frontend/src/shared/NavigatorHotkeys.js]: A better way would be to use the `className` of the `Presenter` so that it is resilient to changes in the future (e.g. you can view the controller on iPad, but this approach would not work since it only includes `desktop`)

File: app/frontend/src/shared/NavigatorHotkeys.js [hunk 2]
```diff
@@ -72,7 +72,9 @@ const NavigatorHotKeys = ( { active, children, mouseTargetRef } ) => {
     }
   }, [ lines, lineId ] )
 
-  const goNextLine = useCallback( () => {
+  const goNextLine = useCallback((e) => {
```
Comment (Harjot1Singh) [inline app/frontend/src/shared/NavigatorHotkeys.js]: Ey ey, use the linter! Style is wrong

Comment (Harjot1Singh) [reply app/frontend/src/shared/NavigatorHotkeys.js]: Also, always prefer being a little more explicit with `event` over `e`

**Comment by AkalUstat** [comment]
> Also need to check on edge cases:
> 
>     * [ ]  Click on lines within presenter should still allow toggle next line

yea it works

File: app/frontend/src/shared/NavigatorHotkeys.js (hunk 1 above)
Comment (AkalUstat) [reply app/frontend/src/shared/NavigatorHotkeys.js]: im not sure i understand

Comment (AkalUstat) [reply app/frontend/src/shared/NavigatorHotkeys.js]: Screen Shot 2020-03-17 at 3 54 34 PM
for example if i clicked the main view area it gave me classname 'desktop app
 and at the bottom it gave me 'presenter'

Comment (Harjot1Singh) [reply app/frontend/src/shared/NavigatorHotkeys.js]: I meant, programmatically acquire the `className` from the ref of the presenter. That way, if we change the presenter className for whatever reason, we won't have a regression here because we forgot to update it here too.

Comment (AkalUstat) [reply app/frontend/src/shared/NavigatorHotkeys.js]: not sure i get it still

**Comment by AkalUstat** [comment]
@bhajneet @Harjot1Singh This is ready for review

File: app/frontend/src/shared/NavigatorHotkeys.js [hunk 3]
```diff
@@ -72,7 +72,17 @@ const NavigatorHotKeys = ( { active, children, mouseTargetRef } ) => {
...
+  const goNextLine = useCallback( e => {
+    const { current: mouseTarget } = mouseTargetRef
+
+    const targetClass = e.target.className
+    const parentClass = e.target.parentNode.className
+    /* Near the bottom of the screen the targetClass
+    becomes 'controller-container` instead of presenter.
+    In this case, we check the targetClass or its parent node's class
+    (which if the target is controller container, will be presenter) */
+    if ( mouseTarget.className !== targetClass
```
Comment (AkalUstat) [inline app/frontend/src/shared/NavigatorHotkeys.js:84]: We can use De Morgan’s law to make this more readable imo.
```js
if(!(mouseTarget.className === targetClass || mouseTarget.className === parentClass))

```

Comment (AkalUstat) [reply app/frontend/src/shared/NavigatorHotkeys.js:84]: Well actually it’s perfectly fine as is

Comment (Harjot1Singh) [reply app/frontend/src/shared/NavigatorHotkeys.js:84]: even better `[ targetClass, parentClass ].includes(mouseTarget.className)`

File: app/frontend/src/shared/NavigatorHotkeys.js [hunk 4]
```diff
@@ -72,7 +72,16 @@ const NavigatorHotKeys = ( { active, children, mouseTargetRef } ) => {
     }
   }, [ lines, lineId ] )
 
-  const goNextLine = useCallback( () => {
+  const goNextLine = useCallback( event => {
+    const { current: mouseTarget } = mouseTargetRef
+
+    const targetClass = event.target.className
```
Comment (Harjot1Singh) [inline app/frontend/src/shared/NavigatorHotkeys.js:78]: Destructure `event.target.etc` at the top.

File: app/frontend/src/shared/NavigatorHotkeys.js [hunk 5]
```diff
@@ -72,7 +72,16 @@ const NavigatorHotKeys = ( { active, children, mouseTargetRef } ) => {
...
+    const parentClass = event.target.parentNode.className
+    /* Near the bottom of the screen the targetClass
+    becomes 'controller-container` instead of presenter.
+    In this case, we check the targetClass or its parent node's class
+    (which if the target is controller container, will be presenter) */
+    if ( ![ targetClass, parentClass ].includes( mouseTarget.className ) ) return
```
Comment (Harjot1Singh) [inline app/frontend/src/shared/NavigatorHotkeys.js:84]: I'm not sure if it's just me, but it does look a little strange to have 2 consecutive return statements, consider combining into one?

**Comment by AkalUstat** [comment]
> Just stylistic changes, happy with the rest 👍
> 
> Btw, your commit messages are not quite right, but I'll be squashing this PR anyway.

yea i keep doing brackets for some reason and i use random tags lol
