### PR TITLE
UI Fixes

### LINKED ISSUE #432: Use matching button styles in settings
image

### LINKED ISSUE #474: Next/prev line buttons in controller do nothing
https://media.giphy.com/media/JmyqQi3fSTqY08McnW/giphy.gif

### LINKED ISSUE #492: Info panel's buttons need styling
A background, border, or anything to give away the fact that it's a button to be pressed/clicked

See settings buttons, can use the same. _Also related #432_

### LINKED ISSUE #493: Info panel needs more spacing
image

More space at the red line would separate "info" and "actions" better

### LINKED ISSUE #497: Show "disabled" copy button for bookmarks
Currently the button is missing and looks "broken". However, if this is by design we should "show" that by graying it out and not making it clickable

### PR DESCRIPTION
**Pull request by saihaj**
Closes #432 
Closes #474 
Closes #492 
Closes #493 
Closes #497

### CODE REVIEW

File: app/frontend/src/Controller/Navigator.js [hunk 1]
```diff
@@ -212,9 +212,7 @@ export const Bar = ( { onHover } ) => {
     const firstLine = lines[ 0 ]
     // Go to the previous shabad if the first line is highlighted (but not for banis)
     if ( !bani && lineId === firstLine.id ) controller.previousShabad( shabad.orderId )
```
Comment (Harjot1Singh) [inline app/frontend/src/Controller/Navigator.js:214]: What happens if you press these buttons on the first or last line of a bani? crash i suspect

File: app/frontend/src/Controller/ShabadInfo.css [hunk 2]
```diff
@@ -4,6 +4,24 @@
...
     background-color: var(--controller-background-color);
 }
-.db-viewer-button{
-    padding-right: 10px;
-}
\ No newline at end of file
+
+.popver-buttons {
+    margin-top: 10px;
+    display: flex;
```
Comment (Harjot1Singh) [inline app/frontend/src/Controller/ShabadInfo.css:10]: 2 space indent for all CSS

File: app/frontend/src/Controller/ShabadInfo.css [hunk 3]
```diff
@@ -4,6 +4,24 @@
...
+    justify-content: space-evenly;
+}
+
+.copy-shabad.Mui-disabled{
+    background-color: #6e6b6b44;
+}
+
+.button {
```
Comment (Harjot1Singh) [inline app/frontend/src/Controller/ShabadInfo.css:18]: None of these classes are namespaced to the component = global conflicts

File: app/frontend/src/Settings/DynamicOptions.css [hunk 4]
```diff
@@ -0,0 +1,9 @@
+.reset-to-defaults-button{
```
Comment (Harjot1Singh) [inline app/frontend/src/Settings/DynamicOptions.css:1]: namespace classes

Comment (Harjot1Singh) [reply app/frontend/src/Settings/DynamicOptions.css:1]: and formatting here

File: app/frontend/src/Settings/DynamicOptions.js [hunk 5]
```diff
@@ -48,7 +50,7 @@ OptionSlot.propTypes = { children: node.isRequired }
 export const ResetButton = ( { group, disabled } ) => (
   <OptionGrid container align="center">
     <Grid item {...slotSizes.single}>
-      <Button disabled={disabled} variant="contained" onClick={() => controller.resetSettingGroup( group )}>Reset to defaults</Button>
+      <Button className="reset-to-defaults-button" disabled={disabled} variant="contained" onClick={() => controller.resetSettingGroup( group )}>Reset to defaults</Button>
```
Comment (Harjot1Singh) [inline app/frontend/src/Settings/DynamicOptions.js:53]: Changing the variant is what you need to do to make it look like the other button, no need for CSS

File: app/frontend/src/Controller/Navigator.js (hunk 1 above)
Comment (saihaj) [reply app/frontend/src/Controller/Navigator.js:214]: Yes it crashes

File: app/frontend/src/Settings/DynamicOptions.js (hunk 5 above)
Comment (saihaj) [reply app/frontend/src/Settings/DynamicOptions.js:53]:
```export const Button = ( { className, ...props } ) => (
  <MaterialButton
    variant="contained"
    className={classNames( className, 'button' )}
    {...props}
  />
)
```
This is from `SettingsComponent.js` and the variant is same to what ResetButton has. I think it is CSS because I added the same values defined in `SetttingsComponent.css` and now it looks the same.

File: app/frontend/src/Settings/DynamicOptions.css (hunk 4 above)
Comment (saihaj) [reply app/frontend/src/Settings/DynamicOptions.css:1]: How do I namespace here? This is only a class name specific to button.

Comment (Harjot1Singh) [reply app/frontend/src/Settings/DynamicOptions.css:1]: hmm maybe every component should have the `.dynamic-option` name before their classname. I'd also rename to `reset-button` lol

File: app/frontend/src/Settings/DynamicOptions.js (hunk 5 above)
Comment (Harjot1Singh) [reply app/frontend/src/Settings/DynamicOptions.js:53]: What about what is in LinkButton? Does it have CSS?

File: app/frontend/src/Controller/ShabadInfo.js [hunk 6]
```diff
@@ -77,23 +77,25 @@ const ShabadInfo = () => {
...
+                onClick={() => controller.openExternalUrl( getDbViewerUrl( lineId ) )}
+              >
+              Open Online
+              </Button>
+            </Tooltip>
+
             <Tooltip title="Click to copy this shabad">
-              <Button className="copy-shabad-button" size="small" onClick={onCopyClick}>
-                  Copy Shabad
+              <Button className="copy-shabad button" size="small" disabled={!shabad} onClick={onCopyClick}>
```
Comment (Harjot1Singh) [inline app/frontend/src/Controller/ShabadInfo.js:93]: Is this supposed to be disabled for banis too?

Comment (saihaj) [reply app/frontend/src/Controller/ShabadInfo.js:93]: for now

Comment (saihaj) [reply app/frontend/src/Controller/ShabadInfo.js:93]: https://github.com/ShabadOS/desktop/issues/500#issuecomment-626003131
