### PR TITLE
fix(frontend): copy on first hotkey stroke

### LINKED ISSUE #437: Copy doesn't work on first hotkey stroke
It felt as though the copy function wasn't working the first time every once in a while. Reported by two users.

### PR DESCRIPTION
**Pull request by saihaj**
### Summary of PR
Work around for sudodoki/copy-to-clipboard#90

### Tests for unexpected behavior
* Works on very first hotkey stroke
* Also works when you change shabads 

### Time spent on PR
4 hours

### Linked issues
Fix #437 

### Reviewers
@Harjot1Singh

### CODE REVIEW

File: app/frontend/src/lib/hooks.js [hunk 1]
```diff
@@ -60,9 +60,12 @@ export const useCopyToClipboard = () => {
   const truncate = input => ( input.length > 30 ? `${input.substring( 0, 30 )}...` : input )
 
   const { enqueueSnackbar } = useSnackbar()
-
   return ( text, fallback = 'No text to copy' ) => {
-    if ( text ) copy( text )
+    // Refactor when this is resolved https://github.com/sudodoki/copy-to-clipboard/issues/90
```
Comment (Harjot1Singh) [inline app/frontend/src/lib/hooks.js:64]: Update the comment to include why you are double copying `Double copying due to bug: link`, and move it inside the `if` block
